//
// Generated by dtk
// Translation Unit: d_menu_dmap.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_menu_dmap.h"
#include "d/d_stage.h"
#include "f_op/f_op_msg_mng.h"

/* 801A86A4-801A87CC       .text __ct__9dMd_HIO_cFv */
dMd_HIO_c::dMd_HIO_c() {
    /* Nonmatching */
    field_0x06 = 0;
    field_0x08 = 0;
    field_0x0a = 0xe;
    field_0x0c = 0xe;
    mColor0.r = 0xff; mColor0.g = 0xc4; mColor0.b = 0x00; mColor0.a = 0xff;
    mColor1.r = 0x20; mColor1.g = 0x20; mColor1.b = 0x00; mColor1.a = 0x00;
    field_0x18 = 0x20;
    field_0x1a = 0x20;
    mColor2.r = 0xff; mColor2.g = 0xff; mColor2.b = 0xff; mColor2.a = 0xff;
    mColor3.r = 0x00; mColor3.g = 0x00; mColor3.b = 0x00; mColor3.a = 0x00;
    field_0x24 = 0x10;
    field_0x26 = 0x8;
    mColor4.r = 0xa8; mColor4.g = 0xa8; mColor4.b = 0xa8; mColor4.a = 0xff;
    mColor5.r = 0x40; mColor5.g = 0x20; mColor5.b = 0x00; mColor5.a = 0x00;
    field_0x30 = 0x10;
    field_0x32 = 0x10;
    mColor6.r = 0xff; mColor6.g = 0x00; mColor6.b = 0xff; mColor6.a = 0xff;
    mColor7.r = 0x00; mColor7.g = 0x00; mColor7.b = 0x00; mColor7.a = 0x00;
    field_0x3c = 0x4;
    field_0x3e = 0xa;
    field_0x40 = 0x2;
    field_0x42 = 0x2;
    field_0x44 = 0x2;
    field_0x46 = 0x2;
    field_0x48 = 0x2;
}

/* 801A87CC-801A8818       .text changeFloorTexture__12dMenu_Dmap_cFP7J2DPanei */
void dMenu_Dmap_c::changeFloorTexture(J2DPane*, int) {
    /* Nonmatching */
}

/* 801A8818-801A92D4       .text screenSet__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::screenSet() {
    /* Nonmatching */
}

/* 801A92D4-801A9364       .text dMap_isBossDoor__FP21stage_tgsc_data_class */
void dMap_isBossDoor(stage_tgsc_data_class*) {
    /* Nonmatching */
}

/* 801A9364-801A98EC       .text initialize__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::initialize() {
    /* Nonmatching */
}

/* 801A98EC-801AAE10       .text treasureSet__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::treasureSet() {
    /* Nonmatching */
}

/* 801AAE10-801AB20C       .text treasureDraw__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::treasureDraw() {
    /* Nonmatching */
}

/* 801AB20C-801AB464       .text paneMove__12dMenu_Dmap_cFf */
void dMenu_Dmap_c::paneMove(float) {
    /* Nonmatching */
}

/* 801AB464-801AB630       .text paneAlpha__12dMenu_Dmap_cFf */
void dMenu_Dmap_c::paneAlpha(float) {
    /* Nonmatching */
}

/* 801AB630-801ABC64       .text decAlpha__12dMenu_Dmap_cFf */
void dMenu_Dmap_c::decAlpha(float) {
    /* Nonmatching */
}

/* 801ABC64-801AC00C       .text cursorMove__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::cursorMove() {
    /* Nonmatching */
}

/* 801AC00C-801AC238       .text cursorAnime__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::cursorAnime() {
    /* Nonmatching */
}

/* 801AC238-801AC2D8       .text noteInit__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::noteInit() {
    /* Nonmatching */
}

/* 801AC2D8-801AC2EC       .text noteCheck__12dMenu_Dmap_cFv */
bool dMenu_Dmap_c::noteCheck() {
    return field_0x0972 == 1 ? TRUE : FALSE;
}

/* 801AC2EC-801AC390       .text noteAppear__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::noteAppear() {
    /* Nonmatching */
}

/* 801AC390-801AC590       .text noteOpen__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::noteOpen() {
    /* Nonmatching */
}

/* 801AC590-801AC7C8       .text noteClose__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::noteClose() {
    /* Nonmatching */
}

/* 801AC7C8-801AC8CC       .text noteOpenProc__12dMenu_Dmap_cFs */
void dMenu_Dmap_c::noteOpenProc(short) {
    /* Nonmatching */
}

/* 801AC8CC-801ACDE0       .text itemScale__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::itemScale() {
    /* Nonmatching */
}

/* 801ACDE0-801ACEB8       .text floorInit__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::floorInit() {
    /* Nonmatching */
}

/* 801ACEB8-801AD000       .text mapMove__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::mapMove() {
    /* Nonmatching */
}

/* 801AD000-801AD130       .text mapOffsetY__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::mapOffsetY() {
    /* Nonmatching */
}

/* 801AD130-801AD1A8       .text itemnameMove__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::itemnameMove() {
    /* Nonmatching */
}

/* 801AD1A8-801AD54C       .text dnameSet__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::dnameSet() {
    /* Nonmatching */
}

/* 801AD54C-801ADA04       .text itemnameSet__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::itemnameSet() {
    /* Nonmatching */
}

/* 801ADA04-801AE004       .text itemnoteSet__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::itemnoteSet() {
    /* Nonmatching */
}

/* 801AE004-801AE08C       .text outFontInit__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::outFontInit() {
    /* Nonmatching */
}

/* 801AE08C-801AE204       .text linkAnime__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::linkAnime() {
    /* Nonmatching */
}

/* 801AE204-801AE550       .text bossAnime__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::bossAnime() {
    /* Nonmatching */
}

/* 801AE550-801AE65C       .text bossEyeAnime__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::bossEyeAnime() {
    s16 halfMax = field_0x1e2c / 2;
    field_0xd62++;

    f32 alpha;
    if (field_0x1e36 != 0) {
        if (field_0xd62 < halfMax) {
            alpha = fopMsgM_valueIncrease(halfMax, field_0xd62, 2);
        } else {
            alpha = fopMsgM_valueIncrease(halfMax, field_0x1e2c - field_0xd62, 2);
        }
    } else {
        alpha = 0.0f;
    }

    if (field_0xd62 == field_0x1e2c) {
        field_0xd62 = 0;
        field_0x1e2c = (s16)((int)(cM_rndF(18.0f) + 40.0f) << 1);

        if (field_0x1e36 != 0) {
            field_0x1e36 = 0;
        } else {
            field_0x1e36 = 1;
        }
    }

    fopMsgM_setNowAlpha((fopMsgM_pane_class*)((u8*)this + 0xd2c), alpha);
    fopMsgM_setNowAlpha((fopMsgM_pane_class*)((u8*)this + 0xd64), alpha);
}

/* 801AE65C-801AEB88       .text _create__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::_create() {
    /* Nonmatching */
}

/* 801AEB88-801AED08       .text _delete__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::_delete() {
    /* Nonmatching */
}

/* 801AED08-801AEE90       .text _move__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::_move() {
    /* Nonmatching */
}

/* 801AEE90-801AF0C0       .text _draw__12dMenu_Dmap_cFv */
void dMenu_Dmap_c::_draw() {
    /* Nonmatching */
}

/* 801AF0C0-801AF294       .text _open__12dMenu_Dmap_cFv */
bool dMenu_Dmap_c::_open() {
    /* Nonmatching */
}

/* 801AF294-801AF3B8       .text _close__12dMenu_Dmap_cFv */
bool dMenu_Dmap_c::_close() {
    /* Nonmatching */
}
